# Generated by Django 5.2.8 on 2026-02-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
