# Generated by Django 5.2.8 on 2026-06-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_overpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancehistory',
            name='type',
            field=models.CharField(choices=[('DEBT_ADD', 'Debt Added'), ('PAYMENT', 'Debt Payment'), ('ORDER_PAYMENT', 'Order Payment'), ('REFUND', 'Refund')], max_length=20),
        ),
    ]
