# Generated by Django 5.2.8 on 2026-02-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.CharField(choices=[('standard', 'Standard'), ('economic', 'Economic'), ('premium', 'Premium')], db_index=True, default='standard', max_length=20),
        ),
    ]
