# Generated by Django 5.2.8 on 2026-02-13 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cutting'),
        ('product', '0004_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cutting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='order.cutting'),
        ),
    ]
