# Generated by Django 5.2.8 on 2026-02-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_cutting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cutting',
        ),
    ]
