# Generated by Django 5.2.8 on 2026-02-28 03:51

import django.core.validators
import product.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'JPG', 'JPEG', 'PNG', 'SVG', 'WEBP']), product.utils.check_image_size]),
        ),
    ]
