# Generated by Django 5.2.8 on 2026-04-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_arrival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
