# Generated by Django 5.2.8 on 2026-05-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_arrival_price_in_dollar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
