# Generated by Django 5.2.8 on 2026-06-17 09:59

import django.core.validators
import product.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_product_arrival_price_in_dollar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='arrival_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Arrival Price in USD'),
        ),
        migrations.AlterField(
            model_name='product',
            name='arrival_price_in_sum',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=15, verbose_name='Arrival Price in UZS'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'JPG', 'JPEG', 'PNG', 'SVG', 'WEBP']), product.utils.check_image_size, product.utils.check_image_content]),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Sale Price in USD'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price_in_sum',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=15, verbose_name='Sale Price in UZS'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thick',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
