# Generated by Django 5.2.8 on 2026-06-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_arrival_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Sale Price in USD'),
        ),
    ]
