# Generated by Django 5.2.8 on 2026-05-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='balance',
        ),
    ]
