# Generated by Django 5.2.8 on 2026-02-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0002_currencyrate_acceptance_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptancehistory',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='acceptancehistory',
            name='price_type',
            field=models.CharField(choices=[('dollar', 'Dollar'), ('sum', 'Sum')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
