# Generated by Django 5.2.8 on 2026-02-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0003_acceptancehistory_exchange_rate_and_more'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptance',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='acceptancehistory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='supplier.supplier'),
        ),
    ]
