# Generated by Django 5.2.8 on 2026-02-26 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0004_acceptance_supplier_acceptancehistory_supplier'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptance',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='supplier.supplier'),
        ),
    ]
