# Generated by Django 5.2.8 on 2026-03-09 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0006_alter_acceptance_arrival_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptance',
            name='acceptance_status',
            field=models.CharField(choices=[('accept', 'Accept'), ('waiting', 'Waiting'), ('cancel', 'Cancel')], default='waiting', max_length=10),
        ),
        migrations.AddField(
            model_name='acceptance',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acceptance',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_acceptances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acceptancehistory',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('accept', 'Accept'), ('cancel', 'Cancel')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acceptancehistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
