# Generated by Django 5.2.8 on 2026-03-10 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0007_acceptance_acceptance_status_acceptance_accepted_at_and_more'),
        ('supplier', '0002_supplier_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptancehistory',
            name='acceptance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='acceptance.acceptance'),
        ),
        migrations.AlterField(
            model_name='acceptancehistory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acceptance_histories', to='supplier.supplier'),
        ),
    ]
