# Generated by Django 5.2.8 on 2026-04-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0010_alter_acceptancehistory_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptancehistory',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
