# Generated by Django 5.2.8 on 2026-05-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0012_acceptance_arrival_price_in_dollar'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptance',
            name='arrival_price_in_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='acceptance',
            name='sale_price_in_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
