# Generated by Django 5.2.8 on 2026-05-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0013_acceptance_arrival_price_in_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptance',
            name='count',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
