# Generated by Django 5.2.8 on 2026-06-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0017_alter_acceptancehistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptance',
            name='arrival_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='arrival_price_in_dollar',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='arrival_price_in_sum',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='count',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='sale_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='sale_price_in_dollar',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='sale_price_in_sum',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='acceptancehistory',
            name='arrival_price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='acceptancehistory',
            name='sale_price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
