# Generated by Django 5.2.8 on 2026-06-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_suppliertransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='overpayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
