# Generated by Django 5.2.8 on 2026-06-04 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_alter_expenseshistory_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('services_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='utils.servicesname')),
            ],
        ),
    ]
