# Generated by Django 5.2.8 on 2026-06-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_servicesname_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='total_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
