# Generated by Django 5.2.8 on 2026-06-17 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_overpayment'),
        ('utils', '0006_services_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='covered_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='services',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='services',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='services',
            name='discount_type',
            field=models.CharField(choices=[('p', 'Foiz'), ('c', 'Naqd')], default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='services',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Kart'), ('nasiya', 'Nasiya')], default='cash', max_length=20),
        ),
    ]
