# Generated by Django 5.2.8 on 2026-07-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_services_covered_amount_services_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='type',
            field=models.CharField(choices=[('Sex', 'Sex'), ('Boshqa', 'Boshqa')], default='Boshqa', max_length=10),
        ),
    ]
