# Generated by Django 5.2.8 on 2026-07-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_alter_expenses_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='type',
            field=models.CharField(choices=[('Zavod', 'Zavod'), ('Boshqa', 'Boshqa')], default='Boshqa', max_length=10),
        ),
    ]
