# Generated by Django 5.2.8 on 2026-02-13 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cutting'),
        ('product', '0006_remove_product_cutting'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutting',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
