# Generated by Django 5.2.8 on 2026-02-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cutting_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutting',
            name='product',
        ),
    ]
