# Generated by Django 5.2.8 on 2026-02-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('nasiya', 'Nasiya'), ('mixed', 'Mixed')], default='cash', max_length=20),
        ),
    ]
