# Generated by Django 5.2.8 on 2026-02-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
