# Generated by Django 5.2.8 on 2026-02-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_banding_created_at_cutting_created_at'),
        ('product', '0007_quality'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='basketitem',
            constraint=models.UniqueConstraint(fields=('basket', 'product'), name='unique_product_per_basket'),
        ),
    ]
