# Generated by Django 5.2.8 on 2026-03-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_basketitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banding',
            old_name='height',
            new_name='length',
        ),
        migrations.RemoveField(
            model_name='banding',
            name='width',
        ),
        migrations.RemoveField(
            model_name='thickness',
            name='size',
        ),
        migrations.AddField(
            model_name='thickness',
            name='text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
