# Generated by Django 5.2.8 on 2026-03-05 10:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_rename_height_banding_length_remove_banding_width_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('accept', 'Accept'), ('waiting', 'Waiting'), ('cancel', 'Cancel')], default='waiting', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('seller', 'Seller'), ('cashier', 'Cashier')], default='seller', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('accept', 'Accept'), ('cancel', 'Cancel'), ('update', 'Update')], max_length=20)),
                ('visible_for', models.CharField(choices=[('seller', 'Seller'), ('cashier', 'Cashier')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='order.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
