# Generated by Django 5.2.8 on 2026-03-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_accepted_at_order_accepted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
