# Generated by Django 5.2.8 on 2026-04-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_banding_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banding',
            name='discount_type',
            field=models.CharField(choices=[('p', 'Percentage'), ('c', 'Cash')], default='c', max_length=1),
        ),
        migrations.AlterField(
            model_name='banding',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('nasiya', 'Nasiya')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='discount_type',
            field=models.CharField(choices=[('p', 'Percentage'), ('c', 'Cash')], default='c', max_length=1),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('nasiya', 'Nasiya')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_type',
            field=models.CharField(choices=[('p', 'Percentage'), ('c', 'Cash')], default='c', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('nasiya', 'Nasiya')], default='cash', max_length=20),
        ),
    ]
