# Generated by Django 5.2.8 on 2026-05-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_banding_thickness_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
