# Generated by Django 5.2.8 on 2026-06-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_alter_order_total_price_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('accept', 'Accept'), ('cancel', 'Cancel'), ('update', 'Update')], max_length=20),
        ),
    ]
